### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by dkoci** [kantega/quarkus-ad#1]
I tried to call quarkus rest api (the same one as in this tutorial) from angular frontend. Get cors error in browser. Am I missing something? 

Access to XMLHttpRequest at 'https://login.microsoftonline.com/2173f838-777b-4b31-befe-50559b28a936/oauth2/v2.0/authorize?response_type=code&client_id=c0d442f1-e181-47a5-a2c1-0adda4371b7d&scope=openid+openid+profile+email&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&state=283320a3-8086-41f7-9af3-bc8dcd66bab2' (redirected from 'http://localhost:8080/v1/testsets') from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by oven** [comment]
It looks like you're trying to call a rest resource without a valid token, and quarkus is redirecting you to Microsoft AD for authentication (which won't work, of course, since it's a rest call and not a page view). There are a couple of chapters in the Quarkus documentation that concern this: 

- https://quarkus.io/guides/security-openid-connect-web-authentication#single-page-applications
- https://quarkus.io/guides/security-openid-connect#single-page-applications

I'm sorry I won't be able to provide detailed support on this issue, as this is a bit beyond the scope of this tutorial.

**Comment by dkoci** [comment]
I will dig into it. Thank you!
